[project]
name = "medical-calls-analysis-aws"
version = "0.1.0"
description = "Medical Calls Analysis in AWS"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["boto3>=1.38.3", "ipykernel>=6.29.5", "streamlit>=1.44.1"]
